name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore C:\Users\balaj\OneDrive\Desktop\.NET_Projects\ConsoleApp1\ConsoleApp1.sln

    - name: Build
      run: dotnet build <path-to-your-solution-or-project-file> --no-restore

    - name: Test
      run: dotnet test <path-to-your-solution-or-project-file> --no-build --verbosity normal
